// Spot actions
export const GET_SPOT_REQUEST = 'GET_SPOT_REQUEST';
export const GET_SPOT_SUCCESS = 'GET_SPOT_SUCCESS';
export const GET_SPOT_FAILURE = 'GET_SPOT_FAILURE';

export const GET_SPOTS_REQUEST = 'GET_SPOTS_REQUEST';
export const GET_SPOTS_SUCCESS = 'GET_SPOTS_SUCCESS';
export const GET_SPOTS_FAILURE = 'GET_SPOTS_FAILURE';

export const ADD_SPOT_REQUEST = 'ADD_SPOT_REQUEST';
export const ADD_SPOT_SUCCESS = 'ADD_SPOT_SUCCESS';
export const ADD_SPOT_FAILURE = 'ADD_SPOT_FAILURE';

export const EDIT_SPOT_REQUEST = 'EDIT_SPOT_REQUEST';
export const EDIT_SPOT_SUCCESS = 'EDIT_SPOT_SUCCESS';
export const EDIT_SPOT_FAILURE = 'EDIT_SPOT_FAILURE';

export const DELETE_SPOT_REQUEST = 'DELETE_SPOT_REQUEST';
export const DELETE_SPOT_SUCCESS = 'DELETE_SPOT_SUCCESS';
export const DELETE_SPOT_FAILURE = 'DELETE_SPOT_FAILURE';

export const SORT_SPOTS_BY_PRICE_REQUEST = 'SORT_SPOTS_BY_PRICE_REQUEST';
export const SORT_SPOTS_BY_PRICE_SUCCESS = 'SORT_SPOTS_BY_PRICE';

// Review actions
export const ADD_REVIEW_REQUEST = 'ADD_REVIEW_REQUEST';
export const ADD_REVIEW_SUCCESS = 'ADD_REVIEW_SUCCESS';
export const ADD_REVIEW_FAILURE = 'ADD_REVIEW_FAILURE';

export const EDIT_REVIEW_REQUEST = 'EDIT_REVIEW_REQUEST';
export const EDIT_REVIEW_SUCCESS = 'EDIT_REVIEW_SUCCESS';
export const EDIT_REVIEW_FAILURE = 'EDIT_REVIEW_FAILURE';

export const DELETE_REVIEW_REQUEST = 'DELETE_REVIEW_REQUEST';
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS';
export const DELETE_REVIEW_FAILURE = 'DELETE_REVIEW_FAILURE';
